<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("medications"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create medications</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('medications/create') ?>" class="form-horizontal" method="post">
<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("name", $medication->name, ["size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
